openapi: 3.0.0
info:
  description: EVO ZWAGGAH
  version: 3.0.0
  title: EVO ZWAGGAH
  contact:
    email: azdevteam@microsoft.com

components:
  schemas:
    Round:
      type: object
      required:
        - name
        - roundId
        - editId
        - created
        - answers
        - templateId
        - authorizedUsers
        - authorizedUserIds
      description: A round
      properties:
        name:
          type: string
        roundId:
          type: string
        editId:
          type: string
        authorizedUsers:
          type: object # Assuming this should be an object, adjust if needed
        authorizedUserIds:
          type: array # Corrected this line
          items:
            type: string
        created:
          type: string
          format: date
        answers:
          type: array
        templateId:
          type: string
paths:
  /round/edit/{editId}:
    get:
      operationId: GetEditRound
      summary: Gets an Edit round
      tags:
        - Round
      parameters:
        - name: editId
          in: path
          required: true
          description: ID of the edit
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Round"

  /round/view/{id}:
    get:
      operationId: GetEditRound
      summary: Gets an Edit round
      tags:
        - Round
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the edit
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Round"
